### ISSUE TITLE
Readme should include directions on getting fcgi

### ISSUE THREAD

**Issue by sdgandhi** [paulofaria/HTTP-Server#2]
fcgi isn't a common library that people will have on their machines so some directions would increase adoption of SwiftHTTPServer.

Readme could include:

---

Download from here: http://www.fastcgi.com/dist/fcgi.tar.gz

```
./configure
make
make install
```

---

**Comment by paulofaria** [comment]
Added to README. I'm focusing on other related projects right now. This project isn't ready for the public yet. I'm planning a major refactor soon. I wish apple would fix the problem with swift frameworks and command line applications. It would be much easier to maintain individual frameworks that connect together. Having everything packed together here is very confusing and causes problems like this FCGI dependency which a lot of people don't even care about.

**Comment by paulofaria** [comment]
Since we're on this, did you have any other dependency related issues?
