### ISSUE TITLE
Example server does not authenticate correctly

### ISSUE THREAD

**Issue by sdgandhi** [paulofaria/HTTP-Server#3]
The example server doesn't authenticate correctly when using `email@email.com` and `password` at /login. I just get an error back `Missing field: email.`

**Comment by paulofaria** [comment]
The url encoded parser was missing. I added it to the specific route, but it could be added before the router, so all routes would get the same effect.

``` swift
let respond = Middleware.parseURLEncoded >>> HTTPRouter { router in
    router.get("/login", LoginResponder.show)
    router.post("/login", LoginResponder.authenticate)

    ...
}
```
