### ISSUE TITLE
The userResponder put/create does not pick up url parameters

### ISSUE THREAD

**Issue by sdgandhi** [paulofaria/HTTP-Server#4]
I'm POSTing to: `localhost:8080/users?name=sid` with basic authentication `username=username` `password=password`, but I get a 400 response back with `Missing field: name.`

**Comment by paulofaria** [comment]
You should send the name in the post body with url encoded content, something like:

``` http
POST /users HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Content-Length: 8

name=sid
```

But for that to work you also have to put the url encoded parser in the specific route or in the router itself, like so:

``` swift
struct ExampleServer {
    static let respond = Middleware.parseURLEncoded >>> HTTPRouter { router in
        ...
    }
}
```

Updated the router with this change.

**Comment by sdgandhi** [comment]
Okay yeah, I tried adding it to the post body, but obviously that didn't work before your change either. Thanks!
