### ISSUE TITLE
Make SwiftHTTPServer a framework

### ISSUE THREAD

**Issue by sdgandhi** [paulofaria/HTTP-Server#5]
Opening this to track progress.

See:
- https://colemancda.github.io/programming/2015/02/12/embedded-swift-frameworks-osx-command-line-tools/
- http://colemancda.github.io/programming/2015/02/11/universal-ios-osx-framework/

I got it almost working, just getting caught up with a bridging header issue.

**Comment by paulofaria** [comment]
SwiftHTTPServer is outdated. I'm rewriting most of SwiftHTTPServer and separating everything in different repos here https://github.com/Zewo.

I finished the HTTP Server part and now I'm going to focus on the HTTP Router. Feel free to continue this, if you want to. The repos at Zewo have a good example on how to make swift frameworks that wrap C libraries. Colin Drake also made a post about it based on Venice (former SwiftGo) http://colinfdrake.com/2015/10/05/wrapping-a-c-library-in-a-swift-framework/.

**Comment by sdgandhi** [comment]
@paulofaria Sweet. I'll see you over at /Zewo then
